const countries = [
    { name: "Afghanistan", code: "AF", currency: "AFN", flag: "af" },
    { name: "Albania", code: "AL", currency: "ALL", flag: "al" },
    { name: "Algeria", code: "DZ", currency: "DZD", flag: "dz" },
    { name: "Andorra", code: "AD", currency: "EUR", flag: "ad" },
    { name: "Angola", code: "AO", currency: "AOA", flag: "ao" },
    { name: "Antigua and Barbuda", code: "AG", currency: "XCD", flag: "ag" },
    { name: "Argentina", code: "AR", currency: "ARS", flag: "ar" },
    { name: "Armenia", code: "AM", currency: "AMD", flag: "am" },
    { name: "Australia", code: "AU", currency: "AUD", flag: "au" },
    { name: "Austria", code: "AT", currency: "EUR", flag: "at" },
    { name: "Azerbaijan", code: "AZ", currency: "AZN", flag: "az" },
    { name: "Bahamas", code: "BS", currency: "BSD", flag: "bs" },
    { name: "Bahrain", code: "BH", currency: "BHD", flag: "bh" },
    { name: "Bangladesh", code: "BD", currency: "BDT", flag: "bd" },
    { name: "Barbados", code: "BB", currency: "BBD", flag: "bb" },
    { name: "Belarus", code: "BY", currency: "BYN", flag: "by" },
    { name: "Belgium", code: "BE", currency: "EUR", flag: "be" },
    { name: "Belize", code: "BZ", currency: "BZD", flag: "bz" },
    { name: "Benin", code: "BJ", currency: "XOF", flag: "bj" },
    { name: "Bhutan", code: "BT", currency: "BTN", flag: "bt" },
    { name: "Bolivia", code: "BO", currency: "BOB", flag: "bo" },
    { name: "Bosnia and Herzegovina", code: "BA", currency: "BAM", flag: "ba" },
    { name: "Botswana", code: "BW", currency: "BWP", flag: "bw" },
    { name: "Brazil", code: "BR", currency: "BRL", flag: "br" },
    { name: "Brunei", code: "BN", currency: "BND", flag: "bn" },
    { name: "Bulgaria", code: "BG", currency: "BGN", flag: "bg" },
    { name: "Burkina Faso", code: "BF", currency: "XOF", flag: "bf" },
    { name: "Burundi", code: "BI", currency: "BIF", flag: "bi" },
    { name: "Cabo Verde", code: "CV", currency: "CVE", flag: "cv" },
    { name: "Cambodia", code: "KH", currency: "KHR", flag: "kh" },
    { name: "Cameroon", code: "CM", currency: "XAF", flag: "cm" },
    { name: "Canada", code: "CA", currency: "CAD", flag: "ca" },
    { name: "Central African Republic", code: "CF", currency: "XAF", flag: "cf" },
    { name: "Chad", code: "TD", currency: "XAF", flag: "td" },
    { name: "Chile", code: "CL", currency: "CLP", flag: "cl" },
    { name: "China", code: "CN", currency: "CNY", flag: "cn" },
    { name: "Colombia", code: "CO", currency: "COP", flag: "co" },
    { name: "Comoros", code: "KM", currency: "KMF", flag: "km" },
    { name: "Congo, Democratic Republic of the", code: "CD", currency: "CDF", flag: "cd" },
    { name: "Congo, Republic of the", code: "CG", currency: "XAF", flag: "cg" },
    { name: "Costa Rica", code: "CR", currency: "CRC", flag: "cr" },
    { name: "Croatia", code: "HR", currency: "EUR", flag: "hr" },
    { name: "Cuba", code: "CU", currency: "CUP", flag: "cu" },
    { name: "Cyprus", code: "CY", currency: "EUR", flag: "cy" },
    { name: "Czech Republic", code: "CZ", currency: "CZK", flag: "cz" },
    { name: "Denmark", code: "DK", currency: "DKK", flag: "dk" },
    { name: "Djibouti", code: "DJ", currency: "DJF", flag: "dj" },
    { name: "Dominica", code: "DM", currency: "XCD", flag: "dm" },
    { name: "Dominican Republic", code: "DO", currency: "DOP", flag: "do" },
    { name: "Ecuador", code: "EC", currency: "USD", flag: "ec" },
    { name: "Egypt", code: "EG", currency: "EGP", flag: "eg" },
    { name: "El Salvador", code: "SV", currency: "USD", flag: "sv" },
    { name: "Equatorial Guinea", code: "GQ", currency: "XAF", flag: "gq" },
    { name: "Eritrea", code: "ER", currency: "ERN", flag: "er" },
    { name: "Estonia", code: "EE", currency: "EUR", flag: "ee" },
    { name: "Eswatini", code: "SZ", currency: "SZL", flag: "sz" },
    { name: "Ethiopia", code: "ET", currency: "ETB", flag: "et" },
    { name: "Fiji", code: "FJ", currency: "FJD", flag: "fj" },
    { name: "Finland", code: "FI", currency: "EUR", flag: "fi" },
    { name: "France", code: "FR", currency: "EUR", flag: "fr" },
    { name: "Gabon", code: "GA", currency: "XAF", flag: "ga" },
    { name: "Gambia", code: "GM", currency: "GMD", flag: "gm" },
    { name: "Georgia", code: "GE", currency: "GEL", flag: "ge" },
    { name: "Germany", code: "DE", currency: "EUR", flag: "de" },
    { name: "Ghana", code: "GH", currency: "GHS", flag: "gh" },
    { name: "Greece", code: "GR", currency: "EUR", flag: "gr" },
    { name: "Grenada", code: "GD", currency: "XCD", flag: "gd" },
    { name: "Guatemala", code: "GT", currency: "GTQ", flag: "gt" },
    { name: "Guinea", code: "GN", currency: "GNF", flag: "gn" },
    { name: "Guinea-Bissau", code: "GW", currency: "XOF", flag: "gw" },
    { name: "Guyana", code: "GY", currency: "GYD", flag: "gy" },
    { name: "Haiti", code: "HT", currency: "HTG", flag: "ht" },
    { name: "Honduras", code: "HN", currency: "HNL", flag: "hn" },
    { name: "Hungary", code: "HU", currency: "HUF", flag: "hu" },
    { name: "Iceland", code: "IS", currency: "ISK", flag: "is" },
    { name: "India", code: "IN", currency: "INR", flag: "in" },
    { name: "Indonesia", code: "ID", currency: "IDR", flag: "id" },
    { name: "Iran", code: "IR", currency: "IRR", flag: "ir" },
    { name: "Iraq", code: "IQ", currency: "IQD", flag: "iq" },
    { name: "Ireland", code: "IE", currency: "EUR", flag: "ie" },
    { name: "Israel", code: "IL", currency: "ILS", flag: "il" },
    { name: "Italy", code: "IT", currency: "EUR", flag: "it" },
    { name: "Jamaica", code: "JM", currency: "JMD", flag: "jm" },
    { name: "Japan", code: "JP", currency: "JPY", flag: "jp" },
    { name: "Jordan", code: "JO", currency: "JOD", flag: "jo" },
    { name: "Kazakhstan", code: "KZ", currency: "KZT", flag: "kz" },
    { name: "Kenya", code: "KE", currency: "KES", flag: "ke" },
    { name: "Kiribati", code: "KI", currency: "AUD", flag: "ki" },
    { name: "Korea, North", code: "KP", currency: "KPW", flag: "kp" },
    { name: "Korea, South", code: "KR", currency: "KRW", flag: "kr" },
    { name: "Kuwait", code: "KW", currency: "KWD", flag: "kw" },
    { name: "Kyrgyzstan", code: "KG", currency: "KGS", flag: "kg" },
    { name: "Laos", code: "LA", currency: "LAK", flag: "la" },
    { name: "Latvia", code: "LV", currency: "EUR", flag: "lv" },
    { name: "Lebanon", code: "LB", currency: "LBP", flag: "lb" },
    { name: "Lesotho", code: "LS", currency: "LSL", flag: "ls" },
    { name: "Liberia", code: "LR", currency: "LRD", flag: "lr" },
    { name: "Libya", code: "LY", currency: "LYD", flag: "ly" },
    { name: "Liechtenstein", code: "LI", currency: "CHF", flag: "li" },
    { name: "Lithuania", code: "LT", currency: "EUR", flag: "lt" },
    { name: "Luxembourg", code: "LU", currency: "EUR", flag: "lu" },
    { name: "Madagascar", code: "MG", currency: "MGA", flag: "mg" },
    { name: "Malawi", code: "MW", currency: "MWK", flag: "mw" },
    { name: "Malaysia", code: "MY", currency: "MYR", flag: "my" },
    { name: "Maldives", code: "MV", currency: "MVR", flag: "mv" },
    { name: "Mali", code: "ML", currency: "XOF", flag: "ml" },
    { name: "Malta", code: "MT", currency: "EUR", flag: "mt" },
    { name: "Marshall Islands", code: "MH", currency: "USD", flag: "mh" },
    { name: "Mauritania", code: "MR", currency: "MRU", flag: "mr" },
    { name: "Mauritius", code: "MU", currency: "MUR", flag: "mu" },
    { name: "Mexico", code: "MX", currency: "MXN", flag: "mx" },
    { name: "Micronesia", code: "FM", currency: "USD", flag: "fm" },
    { name: "Moldova", code: "MD", currency: "MDL", flag: "md" },
    { name: "Monaco", code: "MC", currency: "EUR", flag: "mc" },
    { name: "Mongolia", code: "MN", currency: "MNT", flag: "mn" },
    { name: "Montenegro", code: "ME", currency: "EUR", flag: "me" },
    { name: "Morocco", code: "MA", currency: "MAD", flag: "ma" },
    { name: "Mozambique", code: "MZ", currency: "MZN", flag: "mz" },
    { name: "Myanmar", code: "MM", currency: "MMK", flag: "mm" },
    { name: "Namibia", code: "NA", currency: "NAD", flag: "na" },
    { name: "Nauru", code: "NR", currency: "AUD", flag: "nr" },
    { name: "Nepal", code: "NP", currency: "NPR", flag: "np" },
    { name: "Netherlands", code: "NL", currency: "EUR", flag: "nl" },
    { name: "New Zealand", code: "NZ", currency: "NZD", flag: "nz" },
    { name: "Nicaragua", code: "NI", currency: "NIO", flag: "ni" },
    { name: "Niger", code: "NE", currency: "XOF", flag: "ne" },
    { name: "Nigeria", code: "NG", currency: "NGN", flag: "ng" },
    { name: "North Macedonia", code: "MK", currency: "MKD", flag: "mk" },
    { name: "Norway", code: "NO", currency: "NOK", flag: "no" },
    { name: "Oman", code: "OM", currency: "OMR", flag: "om" },
    { name: "Pakistan", code: "PK", currency: "PKR", flag: "pk" },
    { name: "Palau", code: "PW", currency: "USD", flag: "pw" },
    { name: "Panama", code: "PA", currency: "PAB", flag: "pa" },
    { name: "Papua New Guinea", code: "PG", currency: "PGK", flag: "pg" },
    { name: "Paraguay", code: "PY", currency: "PYG", flag: "py" },
    { name: "Peru", code: "PE", currency: "PEN", flag: "pe" },
    { name: "Philippines", code: "PH", currency: "PHP", flag: "ph" },
    { name: "Poland", code: "PL", currency: "PLN", flag: "pl" },
    { name: "Portugal", code: "PT", currency: "EUR", flag: "pt" },
    { name: "Qatar", code: "QA", currency: "QAR", flag: "qa" },
    { name: "Romania", code: "RO", currency: "RON", flag: "ro" },
    { name: "Russia", code: "RU", currency: "RUB", flag: "ru" },
    { name: "Rwanda", code: "RW", currency: "RWF", flag: "rw" },
    { name: "Saint Kitts and Nevis", code: "KN", currency: "XCD", flag: "kn" },
    { name: "Saint Lucia", code: "LC", currency: "XCD", flag: "lc" },
    { name: "Saint Vincent and the Grenadines", code: "VC", currency: "XCD", flag: "vc" },
    { name: "Samoa", code: "WS", currency: "WST", flag: "ws" },
    { name: "San Marino", code: "SM", currency: "EUR", flag: "sm" },
    { name: "Sao Tome and Principe", code: "ST", currency: "STN", flag: "st" },
    { name: "Saudi Arabia", code: "SA", currency: "SAR", flag: "sa" },
    { name: "Senegal", code: "SN", currency: "XOF", flag: "sn" },
    { name: "Serbia", code: "RS", currency: "RSD", flag: "rs" },
    { name: "Seychelles", code: "SC", currency: "SCR", flag: "sc" },
    { name: "Sierra Leone", code: "SL", currency: "SLL", flag: "sl" },
    { name: "Singapore", code: "SG", currency: "SGD", flag: "sg" },
    { name: "Slovakia", code: "SK", currency: "EUR", flag: "sk" },
    { name: "Slovenia", code: "SI", currency: "EUR", flag: "si" },
    { name: "Solomon Islands", code: "SB", currency: "SBD", flag: "sb" },
    { name: "Somalia", code: "SO", currency: "SOS", flag: "so" },
    { name: "South Africa", code: "ZA", currency: "ZAR", flag: "za" },
    { name: "South Sudan", code: "SS", currency: "SSP", flag: "ss" },
    { name: "Spain", code: "ES", currency: "EUR", flag: "es" },
    { name: "Sri Lanka", code: "LK", currency: "LKR", flag: "lk" },
    { name: "Sudan", code: "SD", currency: "SDG", flag: "sd" },
    { name: "Suriname", code: "SR", currency: "SRD", flag: "sr" },
    { name: "Sweden", code: "SE", currency: "SEK", flag: "se" },
    { name: "Switzerland", code: "CH", currency: "CHF", flag: "ch" },
    { name: "Syria", code: "SY", currency: "SYP", flag: "sy" },
    { name: "Taiwan", code: "TW", currency: "TWD", flag: "tw" },
    { name: "Tajikistan", code: "TJ", currency: "TJS", flag: "tj" },
    { name: "Tanzania", code: "TZ", currency: "TZS", flag: "tz" },
    { name: "Thailand", code: "TH", currency: "THB", flag: "th" },
    { name: "Timor-Leste", code: "TL", currency: "USD", flag: "tl" },
    { name: "Togo", code: "TG", currency: "XOF", flag: "tg" },
    { name: "Tonga", code: "TO", currency: "TOP", flag: "to" },
    { name: "Trinidad and Tobago", code: "TT", currency: "TTD", flag: "tt" },
    { name: "Tunisia", code: "TN", currency: "TND", flag: "tn" },
    { name: "Turkey", code: "TR", currency: "TRY", flag: "tr" },
    { name: "Turkmenistan", code: "TM", currency: "TMT", flag: "tm" },
    { name: "Tuvalu", code: "TV", currency: "AUD", flag: "tv" },
    { name: "Uganda", code: "UG", currency: "UGX", flag: "ug" },
    { name: "Ukraine", code: "UA", currency: "UAH", flag: "ua" },
    { name: "United Arab Emirates", code: "AE", currency: "AED", flag: "ae" },
    { name: "United Kingdom", code: "GB", currency: "GBP", flag: "gb" },
    { name: "United States", code: "US", currency: "USD", flag: "us" },
    { name: "Uruguay", code: "UY", currency: "UYU", flag: "uy" },
    { name: "Uzbekistan", code: "UZ", currency: "UZS", flag: "uz" },
    { name: "Vanuatu", code: "VU", currency: "VUV", flag: "vu" },
    { name: "Vatican City", code: "VA", currency: "EUR", flag: "va" },
    { name: "Venezuela", code: "VE", currency: "VES", flag: "ve" },
    { name: "Vietnam", code: "VN", currency: "VND", flag: "vn" },
    { name: "Yemen", code: "YE", currency: "YER", flag: "ye" },
    { name: "Zambia", code: "ZM", currency: "ZMW", flag: "zm" },
    { name: "Zimbabwe", code: "ZW", currency: "ZWL", flag: "zw" }
];

const languages = [
    { name: "English", code: "en" },
    { name: "Urdu", code: "ur" },
    { name: "Arabic", code: "ar" },
    { name: "Hindi", code: "hi" },
    { name: "Spanish", code: "es" },
    { name: "French", code: "fr" },
    { name: "German", code: "de" },
    { name: "Italian", code: "it" },
    { name: "Portuguese", code: "pt" },
    { name: "Russian", code: "ru" },
    { name: "Chinese (Simplified)", code: "zh-CN" },
    { name: "Chinese (Traditional)", code: "zh-TW" },
    { name: "Japanese", code: "ja" },
    { name: "Korean", code: "ko" },
    { name: "Turkish", code: "tr" },
    { name: "Bengali", code: "bn" },
    { name: "Punjabi", code: "pa" },
    { name: "Malay", code: "ms" },
    { name: "Indonesian", code: "id" },
    { name: "Vietnamese", code: "vi" },
    { name: "Thai", code: "th" },
    { name: "Dutch", code: "nl" },
    { name: "Greek", code: "el" },
    { name: "Swedish", code: "sv" },
    { name: "Norwegian", code: "no" },
    { name: "Danish", code: "da" },
    { name: "Finnish", code: "fi" },
    { name: "Polish", code: "pl" },
    { name: "Czech", code: "cs" },
    { name: "Slovak", code: "sk" },
    { name: "Hungarian", code: "hu" },
    { name: "Romanian", code: "ro" },
    { name: "Bulgarian", code: "bg" },
    { name: "Croatian", code: "hr" },
    { name: "Serbian", code: "sr" },
    { name: "Hebrew", code: "he" },
    { name: "Persian", code: "fa" },
    { name: "Pashto", code: "ps" },
    { name: "Sindhi", code: "sd" },
    { name: "Balochi", code: "bal" }
];

export { countries, languages };
